### ISSUE TITLE
blaze-magic-events countered by autoform's anti-magic field

### ISSUE THREAD

**Issue by mordrax** [themeteorites/blaze-magic-events#2]
```
+afFieldInput name="cardnumber" onchange="{{validateCard}}"
```

The above code is not converted to a event hook, but rather stays a boring:

```
<input name="cardnumber" onchange="{{validateCard}}">
```

**Comment by seeekr** [comment]
That's (presumably) because in the context of calling a template (which afFieldInput is) the way to pass the result from a helper is like this:

`+afFieldInput name="cardnumber" onchange=validateCard`

This is already treated as code and thus no braces are necessary to designate "code" as opposed to "html text". Like that it should work.

**Comment by mordrax** [comment]
Thanks for the quick turnaround. Actually, because of this and not wanting to let go of this awesome package, I rewrote my autoforms to just use normal html but still retain manual validation, doc insert helpers, simpleschema fields. So I was able to take a styled html snipplet, apply my schema, get validation for free and then hook up the events and query autoform for the form fields! Christmas come early this year.
