### ISSUE TITLE
more event types

### ISSUE THREAD

**Issue by WayneUong** [themeteorites/blaze-magic-events#6]
Will this support more event types like `input`, `change`, `submit`, `hover` etc..?
Thanks

**Comment by seeekr** [comment]
It does work with any event! You just have to use the regular HTML event name like `onclick` instead of `click`, `onchange` instead of `change`, and this library will do what it's supposed to do. Makes sense?
`blaze-magic-events` is in no way restricted to specific events, it supports all that browsers support.

**Comment by WayneUong** [comment]
wow, that's so awesome, thanks!
